export default {
  bom: {
    title: '物料BOM',
    subTitle: '物料BOM编辑',
    options: {
      waitConfirm: '待确认',
      confirm: '确认',
      cancel: '取消',
      level: '优先级',
      percent: '百分比'
    },
    label: {
      materialCode: '物料编码',
      materialName: '物料名称',
      materialCategory: '物料类别',
      productionType: '生产类型',
      prdProcess: '工段',
      type: '类别',
      typeName: '类别名称',
      version: 'BOM版本',
      effectiveFrom: '生效日期',
      effectiveTo: '失效日期',
      schedulingModel: '排程模型',
      index: '序号',
      applyOrderNo: '组件物料',
      quantity: '用量',
      baseQuantity: '基准数量',
      lossRate: '损耗率',
      fixedLossQuantity: '固定损耗量',
      vendorCode: '供应商代码',
      replaceGroup: '替代项目：组',
      replaceStrategy: '替代组：策略',
      usePossibility: '使用可能性',
      status: '状态',
      material: '物料',
      absent: '不存在',
      bastQuantity: '基本数量'
    },
    placeholder: {
      siteCode: '请选择工厂名称',
      materialCode: '请选择物料编码',
      materialName: '请输入物料名称',
      unit: '请输入单位',
      materialCategory: '请选择物料类别',
      productionType: '请选择生产类型',
      prdProcess: '请选择工段',
      type: '请输入类别',
      typeName: '请输入类别名称',
      version: '请输入BOM版本',
      effectiveFrom: '请选择生效日期',
      effectiveTo: '请选择失效日期',
      remark: '请输入备注',
      schedulingModel: '请选择排程模型',
      quantity: '请输入用量',
      baseQuantity: '请输入基准数量',
      lossRate: '请输入损耗率',
      fixedLossQuantity: '请输入固定损耗量',
      vendorCode: '请输入供应商代码',
      replaceGroup: '请输入替代项目：组',
      replaceStrategy: '请选择替代组：策略',
      usePossibility: '请输入使用可能性',
      status: '请选择状态',
      applyOrderNo: '请填写组件物料',
      bastQuantity: '请输入基本数量'
    },
    message: {
      quantity: '请填用量，最多填写大于0的10位数字且最多保留五位小数',
      baseQuantity: '请填基准数量，最多填写大于0的10位数字且最多保留五位小数',
      lossRate: '正确填写损耗率，最多填写大于0的10位数字且最多保留五位小数',
      fixedLossQuantity: '正确填写固定损耗量，最多填写大于0的10位数字且最多保留五位小数',
      applyOrderNo: '同一主表下，子列表中组件物料不可重复'
    }
  },
}