export default {
    budget:{
        Tshirt: "T-shirt Budget",
        assembly: "Assembly Budget",
        seamless: "Seamless Budget",
        sweater: "Sweater Budget",
        workShop: "Work shop",
        label:{
            site: "Site",
            year: "Year",
            gg:'gg',
            item:'item',
            country: "Country",
            customer: "Customer",
            detail:'Detail',
            season:'Season',
            description: "Description",
            process: "Process",
            program: "Program",
            focus: "Focus",
            mcSize: "MC Size",
            workShop: "Work shop",
            Unit: "Unit",
            Jan: "Jan",
            Feb: "Feb",
            Mar: "Mar",
            Apr: "Apr",
            May: "May",
            Jun: "Jun",
            Jul: "Jul",
            Aug: "Aug",
            Sep: "Sep",
            Oct: "Oct",
            Nov: "Nov",
            Dec: "Dec",
        },
        placeholder: {
            dictName: "请输入字典名称",
            dictType: "请输入字典类型",
            dictItemLabel:"请输入字典标签",
            dictItemKey:"请输入字典键值",
            dictItemSort:"请输入字典排序",
            updata:'导入数据已存在，请确认是否替换已存在数据！',
            upload:'请选择导入文件',
            year:"请选择year",
            site:"请选择site",
        },
        selectCommon:{
            TshirtBudget:"T-shirt-Budget",
            TshirtLoading:"T-shirt-Loading",
            assemblyBudget:"Assembly-Budget",
            assemblyLoading:"Assembly-Loading",
            seamlessBudget:"Seamless-Budget",
            seamlessLoading:"Seamless-Loading",
            sweaterBudget:"Sweater-Budget",
            sweaterLoading:"Sweater-Loading",
            workShopBudget:"Work shop",
            workShopLoading:"Customer",
        }
    }
}