export default{
    //mrp物料分配
    calculation:{
        label:{
            "sitecode":"工厂编码",
            "planOrder":"计划订单号",
            "materialCode":"需求物料",
            "demandTime":"需求时间",
            "upperPlanOrder":"上层订单号",
            "materialName":"物料名称",
            "replaceGroup":"替代组",
            "replacePriority":"替代优先级",
            "purchasingGroup":"采购组",
            "aviableQty":"剩余可用库存",
            "arriveQty":"采购到料量",
            "demandDate":"需求日期",
            "demandQty":"需求数量",
            "kittingState":"齐套状态",
            "allocateQty":"分配量",
            "shortageQty":"短缺量",
            "caigouzu":"采购组"
        },
        placeholder:{
            "sceneCode":"请选择场景",
            "searchVersion":"请选择版本号",
        }
    },
}