export default {
  calendar: {
    holiday: '假期日历',
    holidayEdit: '假期日历编辑',
    plan: '计划日历',
    planEdit: '计划日历编辑',
    distribute: '计划日历分配',
    distributeEdit: '计划日历分配编辑',
    label: {
      PUBLIC: '法定假期',
      OTHER: '其它假期',
      NONE: '永不',
      YEAR: '每年',
      MONTH: '每月',
      WEEK: '每周',
      country: '国家',
      holidayName: '假期名称',
      holidayDesc: '假期描述',
      holidayType: '假期类型',
      startDate: '开始日期',
      endDate: '结束日期',
      startTime: '起始时间',
      endTime: '结束时间',
      workDayList: '有效星期',
      repeatType: '重复方式',
      calendarName: '日历名称',
      calendarDesc: '日历描述',
      objectCategory: '对象类别',
      objectId: '对象值',
      objectDesc: '对象描述',
      calendarId: '日历名称',
      valid: '是否有效',
      shiftName: '班次名称',
      shiftDesc: '班次描述',
      duration: '上班时长',
      timeRange: '起止时间',
      validRange: '有效期',
      duty: '班次',
      isWorkDay: '是否工作日',
      remark: '备注',
      weekDaySelect: '工作日',
      date: '日期',
      inputNumber: '投入人数',
    },
    dialog: {
      add: '新增/编辑',
      shift: '班次清单',
      holiday: '假期日历清单',
      planAdd: '计划日历新增',
      planEdit: '计划日历编辑',
    },
    placeholder: {
      country: '请选择国家',
      holidayType: '请选择假期类型',
      holidayName: '请输入假期名称',
      holidayDesc: '请输入假期描述',
      repeatType: '请选择重复方式',
      startDateRange: '请选择起始日期',
      endDateRange: '请选择有效期',
      calendarName: '请输入日历名称',
      calendarSelectName: '请选择日历名称',
      calendarDesc: '请输入日历描述',
      startDate: '请选择开始日期',
      endDate: '请选择结束日期',
      weekDaySelect: '请选择工作日',
      valid: '请选择是否有效',
      date: '请选择日期',
      isWorkDay: '请选择是否工作日',
      remark: '请输入备注',
      objectCategory: '请选择对象类别',
      objectId: '请选择对象值',
      inputNumber: '请输入投入人数',
    },
    button: {
      year: '年',
      month: '月',
      week: '周',
      day: '日',
    },
    tab: {
      first: '主要',
      second: '分配班次',
      third: '分配假期日历',
      fourth: '例外日期'
    },
    ruler: {
      calendarName: '应只包含（[中文、英文、数字]）'
    },
    message: {
      dataRepeat: '数据已添加，不可重复'
    }
  }
}