export default {
    //编码规则
    codeRule: {
        title: "编码规则",//导出文件名
        subTitle: '编码规则新增/编辑',
        childTitle: '编码规则维护',
        childSubTitle: '编码规则值维护新增/编辑',
        label: {
            addRow:'新建行',
            editRow:'编辑行',
            deleteRow:'删除行',
            return:'返回',
            materialGroup: "物料组",
            trasaction: "事务",
            immediate: "即时",
            fixed: "固定字符串",
            var: "可替换参数",
            time: "时间",
            sequence: "自增长序列",
            material: "物料",
            materialVersion: "物料版本",
            shopOrder: "工单",
            opUser: "操作执行人员ID",
            never: "从不",
            day: "每天",
            week: "每周",
            month: "每月",
            year: "每年",
            asc: "顺序",
            desc: "反序",
            all:'所有',
            //编码规则主页面
            codeType: "编码类型",
            definedBy: "定义目标",
            definedContent: "目标内容",
            rev: "版本",
            commitType: "提交类型",
            //编码规则子页面
            sequenceType: "类型",
            fixedString: "固定字符串值",
            varType: "可替换参数值",
            length: "长度",
            numBase: "进制",
            numIncr: "增量",
            initValue: "初始值",
            finalValue: "最终值",
            currentValue: "当前值",
            reset: "循环",
            order: "顺序",
            operation: "操作",
        },
        placeholder: {
            codeType: "请选择编码类型",
            definedBy: "请选择定义目标",
            definedContent: "请选择目标内容",
            definedContentInput: "请输入目标内容",
            definedContentInput1: "请选择目标内容",
            rev: "请选择版本",
            commitType: "请选择提交类型",
            sequenceType: "请选择规则类型",
            fixedString: "请输入固定字符串",
            varType: "请选择可替换参数",
            dateTimeFormatInput: "请输入时间格式化",
            length: "请输入长度",
            numBase: "请输入进制",
            numIncr: "请输入增量",
            initValue: "请输入初始值",
            currentValue: "请输入当前值",
            finalValue: "请输入最终值",
            //子页面form
            sequenceTypeChild: "规则类型",
            dateTimeFormat: "时间格式化",
        },
        rules: {
            fixedString: "应只包含（[A-Z,0-9,-,_,/])",
            length: "只能输入数字",
            lengthRange: "应只包含（[1-10])",
            numBaseRange: "应只在2-36之间",
            numIncrRange: "应只在0-999999之间",
            initValueRange: "不能为负数",
            initValueLength: "初始值长度和长度必须匹配",
            initValueAsc: "当顺序为升序时，初始值应该小于最终值",
            initValueDesc: "当顺序为降序时，初始值应该大于最终值",
            currentValue:'当前值只能输入数字',
            currentValueLength: "当前值长度和长度必须匹配",
            currentValueAsc: "当前值必须在初始值和终值的区间内",
            currentValueDesc: "当前值必须在初始值和终值的区间内",
            finalValueLength: "终值长度和长度必须匹配",
            finalValueAsc: "当顺序为升序时，最终值应该大于初始值",
            finalValueDesc: "当顺序为降序时，最终值应该小于初始值",
            reset: "请选择循环",
            order: "请选择顺序",
        },
    }
}