export default {
  cupPlannedManagement: {
    title: "棉杯计划管理",
    errorLog: "错误日志",
    editTitle: "",
    label: {
      styleNo: "款号",
      componentStyle: "棉杯款号",
      productionDepartmentId: "生产部",
      customerCode: "客户",
      processCategory: "工艺类型",
      processCategorys: "定型工艺",
      componentSize: "棉杯尺码",
      dieSet: "模具配比",
      dieSetQty: "模具套数",
      ptm: "PTM",
      dieQty: "所需机台数",
      changeoverColor: "转色时长",
      changeoverMould: "换模时长",
      unitCode: "单位",
      sizeCodes: "成衣等码",
      orderCode: "销售订单",
      orderLine: "销售订单行",
      combineOrderNo: "组合订单",
      auditingSection: "损耗计算组",
      mo: "生产订单",
      cupDeliveryStart: "棉杯交杯开始期",
      cupDeliveryFinish: "棉杯交杯结束期",
      mainNodeDate: "主料需求到厂期",
      auxiliaryNodeDate: "包材需求到厂期",
      receiveOrderDate: "收单日期",
      productionSite: "成衣工厂",
      orderType: "订单类型",
      preCapacityType: "预产能类型",
      orderState: "订单状态",
      colorDescription: "成衣颜色描述",
      componentColor: "棉杯颜色",
      sapPlanOrderQty: "订单数量",
      taskQty: "需求生产数量",
      deliveryDate: "成衣客期",
      startDateTime: "成衣后工序上线期",
      mainFabricProgress: "主料进度",
      frontProcessProgress: "辅料进度",
      exportDetails: "棉杯排产明细导出",
      taskStatus: "任务状态",
      planStatus: "计划状态",
      errorLogExport:"棉杯计划管理错误日志导出",
      checkCode:"错误编码",
      checkMessage:"错误描述"
    },

    placeholder: {
      productionDepartmentId:"请选择生产部门"
    },
  },
};
