export default {
  cupSchedulingConfig: {
    title: "棉杯排产属性",
    subTitle: "",
    editTitle: "",
    label: {
      componentStyle: "棉杯款号",
      productionDepartmentId: "生产部",
      customerCode: "客户",
      processCategory: "工艺类型",
      processCategorys: "定型工艺",
      componentSize: "棉杯尺码",
      moldingTimes: "定型次数",
      dieSet: "模具配比",
      dieSetQty: "模具套数",
      ptm: "PTM",
      dieQty: "所需机台数",
      changeoverColor: "转色时长",
      changeoverMould: "换模时长",
      unitCode: "单位",
      sizeCodes: "成衣等码",
    },

    placeholder: {
      componentStyle: "请输入棉杯款号",
      productionDepartmentId: "请选择生产部",
      customerCode: "请选择客户",
      processCategory: "请选择工艺类型",
      componentSize: "请输入棉杯尺码",
      moldingTimes: "请输入定型次数",
      dieSet: "请输入模具配比",
      dieSetQty: "请输入模具套数",
      ptm: "请输入PTM",
      dieQty: "请输入所需机台数",
      changeoverColor: "请输入转色时长",
      changeoverMould: "请输入换模时长",
      unitCode: "请输入单位",
      sizeCodes: "请输入成衣等码",
      remark: "请输入备注",
      row: "行数",
      tableData: "表格数据不能为空",
      processCategorys: "请输入定型工艺",
      positiveInteger: "请输入正整数",
      positiveNumber: "请输入正数",
      positiveNumberOrZero: "请输入大于或等于0的数值",
    },
  },
};
