export default {
  //前工序落货计划
  derivePlan: {
    title: "前工序落货计划",
    exportTitleW: "前工序落货计划(周维度)",
    exportTitleM: "前工序落货计划(月维度)",
    label: {
        prdProcess:"工段",
        mo:"工单号",
        productionDepartmentName:"生产部",
        mainFabricDeliveryDate:"主布DGNG到厂期",
        mainFabricPercentage:"主布到料(%)",
        accessoriesDeliveryDate:"辅料DGNG到厂期",
        accessoriesPercentage:"辅料到料(%)",
        colorDescription:"颜色",
        styleNo:"款号",
        qty:"总订单数量",
        monthKittingDate:"月计划锁定配套期",
        weekKittingDate:"周计划锁定配套期",
        itemType:"前后工序",
        planner:"排单员",
        planDate:"计划日期",
        version:"版本",
        actualKittingDate:"配套期",
        orderQty:"组合订单数量",
        processQty:"加工数量",
        taskQty:"计划数量",
        completeQty:"完成数量",
        requirementQty:"欠数",
        unplannedQty:"计划外数量",
        planStartDate:"目标开始日期",
        planEndDate:"目标完成日期",
        actualStartDate:"最早开始日期",
    },
    placeholder: {},
    rules: {},
  },
};
