export default {
  //发染管理
  dyeingManagement: {
    dyeingPlanTitle: "发染计划",
    label: {
      dn: "发染单号",
      deliveryDate: "交货日期",
      dyeingNo: "发染缸号",
      orderNo: "销售订单",
      combineOrderNo: "组合订单",
      mo: "白胚工单",
      styleNo: "成衣款号",
      componentColor: "RM色号",
      status: "状态",
      cred: "创建",
      rel: "下达",
      clsd: "关闭",
      dyeingQty: "发染件数",
      totalWeight: "总重量（kg）",
      orderNo: "订单/合同",
      ingredientRatio: "成分比例",
      dyeingEffiect: "要求效果",
      selectedOrderTotalWeight: "已选订单总重量",
      volume: "容量(kg)",
      color: "颜色",
      remainingSelectableWeight: "剩余可选重量",
      dyeingNoTitle: "发染缸选择",
      dyeVatNo: "缸号",
      selectPendingOrder: "查询待排任务",
      styleNo: "款号",
      pendingQty: "待染数量(件)",
      dyeingQty: "发染数量(件)",
      weight: "重量(g)",
      totalWeight: "总重量(kg)",
      box: "箱",
      deliveryDate1: "客期",
      greyClothMo: "白胚工单号",
      dyeingClothMo: "色胚工单号",
      garmentColor: "成衣颜色",
      size: "尺码",
      capacity: "容量",
    },
    placeholder: {
      styleNo: "请输入成衣款号",
      customerCode: "请输入客户",
      combineOrderNo: "请输入组合订单",
      deliveryDate: "请选择收货时间",
      orderNo: "请输入订单/合同",
      ingredientRatio: "请输入成分比例",
      dyeingEffiect: "请输入要求效果",
      qty: "发染数量不能大于待染数量",
      positiveInteger: "请输入正整数",
    },
    rules: {},
  },
};
