export default {
    //ERP销售订单
    erpSalesOrder: {
      title: 'ERP销售订单',
      subTitle: 'ERP销售订单编辑',
      label: {
        "so":"销售订单号",
        "soItem":"销售订单行号",
        "productType":"产品类型",
        "orderType":"订单类型",
        "productFamilyCode":"产品族",
        "materialCode":"物料编码",
        "materialName":"物料名称",
        "customerName":"客户名称",
        "shipEarly":"是否可提前发货",
        "crsd":"CRSD",
        "crad":"CRAD",
        "unit":"单位",
        "crwd":"要求入库日期",
        "status":"状态",
        "qty":"订单数量",
      },
      placeholder:{
        "so":"请输入销售订单号",
        "soItem":"请输入销售订单行号",
        "productType":"请选择产品类型",
        "orderType":"请选择订单类型",
        "productFamilyCode":"请选择产品族",
        "materialCode":"请选择物料编码",
        "materialName":"请选择物料名称",
        "customerName":"请选择客户名称",
        "shipEarly":"请选择是否可提前发货",
        "crsd":"请选择CRSD",
        "unit":"请选择单位",
        "crad":"请选择CRAD",
        "crwd":"请选择要求入库日期",
        "status":"请选择状态",
        "qty":"请输入订单数量",
      },
      rules:{
        "findRecord":'物料编码不存在,请重新输入',
        "findCustomer":'客户不存在,请重新输入',
        "findSalesOrder":'销售订单不存在,请重新输入',
        "handleCustomerlBlur":'客户名称不存在,请重新输入',
        "handleSpecialCustomerlBlur":'客户不存在,请重新输入',
        "soRules":'销售订单号只能数字和英文字母和-，_,#',
      },
    }
  }