export default {
  materialProgress: {
    title: "物料进度",
    shortageLabel:{
      combineOrderNo: "组合订单号",
      orderCode: "SO号",
      styleNo: "款号",
      customerCode: "客户",
      deliveryDateStr: "货期",
      colorCode: "颜色",
      qtyAll: "订单数量",
      materialGroup: "物料分类",
      materialCode: "物料编码",
      shortageQty: "欠料数量",
      shortageRate: "欠料比例",
      po: "采购PO",
      deliveryDate: "在途日期",
    },
    label: {
      materialProgress: "物料进度",
      shortageInformation: "欠料信息",
      mainMaterialProgress: "主料进度",
      styleNo: "款号",
      combineOrder: "组合订单",
      isShortage: "是否缺料",
      customer: "客户",
      orderQty: "订单数量",
      customerStyleNo: "客户款号",
      process: "基础工艺",
      productType: "产品类型",
      prepareTime: "车缝计划上线时间",
      outputTime: "出产量时间",
      followUpRecoveryPeriod: "跟单复货期",
      originalCustomerPeriod: "客期",
      planCuttingTime: "计划开裁时间",
      planCuttingFabricEarlyDay: "计划开裁vs布最早到厂(天)",
      planCuttingFabricEndDay: "计划开裁vs布最晚到厂(天)",
      materialCycleDay: "物料周期",
      fabricDgngDate: "布需求期",
      fabricDelayDays: "布迟期天数",
      auxiliaryDgngDay: "辅料需求期",
      auxiliaryDelayDays: "辅料迟期天数",
      materialKittingDate: "原材料配套期",
      matchingPeriod: "生产配套期",
      colorCode: "颜色",
      so: "SO号",
      deliveryDate: "货期",
      sewingOnlineDate: "车缝上线日期",
      materialCategory:"物料分类",
      materialCode:"物料编码",
      materialMngPeriod:"物料DGNG期",
      shortageQty:"欠料数量",
      shortageRate:"欠料比例",
      purchasePo:"采购PO",
      inTransitDate:"在途日期",
      materialName:"物料名称",
      totalQty:"需求数量",
      stockQty:"库存数量",
      deliveryQty:"ETA满足量",
      etaDate:"ETA日期",
      po:"采购PO",
      cloth:"布",
      auxiliaryMaterial:"辅料",
      packagingAuxiliaryMaterial:"包装辅材",
      cotton:"棉",
      yarn:"纱线",
      glue:"胶水",
      adhesiveMaterial:"贴合物料",
    },
  },
};
