export default {
  //物料主数据
  materialMaintenance: {
    title: '物料主数据信息',
    subTitle: '物料主数据信息编辑',
    label: {
      materialSpec: "物料规格",
      material: "物料",
      materialState: "物料状态",
      materialType: "产品大类",
      materialSubType: "产品小类",
      safeNum: "安全库存",
      basicUnit: "基本单位",
      productionType: "生产类型",
      //materialCategory:"物料类别",
      materialCategory: "物料类型",
      isKeyPart: "是否关键料",
      uomfactor: '转换比例',
      purchuom: '采购单位',
      size: '尺码',
      color: '颜色编码',
      prdProcess: "工段",
      materialVersion: '工段',
      materialGroup: '物料组',
      vaseValue: '转换比例（基本）',
      transformRate: '转换比例（采购）',
      sizeName: '尺码名称',
      colorName: '颜色名称',
      fabricType: '布种',
      weightBeforeWashing: '洗水前克重',
      weightAfterWashing: '洗水后克重',
      similarStyle: '相似款',
      glueTypeCode: '点胶类型',
      difficultyLevel: '款式难易度',
      subCategory:"产品小类",
      colorCharactor:"颜色特征值代码",
      sizeCharactor:"尺码特征值代码"
    },
    options: {
      normal: "正常",
      disabled: "失效",
      close: "关闭",
    },
    placeholder: {
      fabricType: '请选择布种',
      materialGroup: '请输入物料组',
      weightBeforeWashing: '请输入洗水前克重',
      weightAfterWashing: '请输入洗水后克重',
      sizeName: '请输入尺码名称',
      colorName: '请输入颜色名称',
      vaseValue: '请输入转换比例（基本）',
      transformRate: '请输入转换比例（采购）',
      materialSpec: "请输入物料规格",
      materialState: "请选择物料状态",
      materialCategory: "请选择物料类型",
      safeNum: "请输入安全库存",
      unit: "请选择基本单位",
      productionType: "请选择生产类型",
      materialType: "请选择产品大类",
      materialSubType:"请选择产品小类",
      isKeyPart: "请选择是否关键料",
      prdProcess: "请选择工段",
      itemCategory: '请选择物料分类',
      uomfactor: '请输入比例',
      purchuom: '请选择采购单位',
      size: '请输入尺码',
      color: '请输入颜色编码',
      similarStyle: '请输入相似款',
      glueTypeCode: '请选择点胶类型',
    },
    ruler: {
      checkProductFamily: "产品族名称不存在,请重新输入",
      workSplitRate: '只能输入数字和:',
      trsansformRate: '只允许输入三位小数',
    }
  }
}