export default {
  //pds- 甘特图-订单排产属性
  gannt_orderSchedulingAttribute: {
    label: {
      combinedOrderNo: "组合订单号:",
      styleNo: "款号:",
      customer: "客户:",
      workSection: "工段:",
      nextPrdProcessName: "下一工段:",
      originalCustomerDate: "客期:",
      standardWorkTime: "标工:",
      updatedCustomerDate: "更新后客期:",
      inputStaffCount: "投入人数:",
      targetEfficiency: "目标效率",
      learningCurve: "学习曲线",
      // learningCurveType: "学习曲线/按日产量:",
      dailyOutput: "按日产量",
      climbingRate: "爬坡率",
      historicalEfficiency: "历史效率",
      targetQty: "峰值产量",
      resetProcessRoute: "重读工艺路线",
      simulation: "模拟",
      orderDetai: "订单明细",
      adviseEarlyStartTime: "建议最早开始时间:",
      earlyStartTime: "最早可开始时间:",
      day: "天数",
    },
    tabs: {
      scheduleResult: "排产结果",
      leadTime: "工序等待时间",
      workReport: "报工",
      orderDetai: "订单明细",
    },
    placeholder: {
      combinedOrderNo: "请输入组合订单号",
      styleNo: "请输入款号",
      customer: "请选择客户",
      workSection: "请选择工段",
      originalCustomerDate: "请选择客期",
      standardWorkTime: "请输入标工",
      updatedCustomerDate: "请选择更新后客期",
      inputStaffCount: "请输入投入人数",
      targetEfficiency: "请输入目标效率",
      learningCurve: "请输入学习曲线",
      learningCurveType: "请选择学习曲线/按日产量",
      targetQty: "请输入峰值产量",
    },
  },
};
