export default {
  orderMasterData: {
    title: '销售订单主数据',
    subTitle: '销售订单主数据新增',
    editTitle: '销售订单主数据编辑',
    label: {
      // 订单数据
      siteCode: "工厂编码",
      so: "销售订单",
      orderType: "订单类型",
      series: "系列",
      po: "客户PO",
      productFamilyCode: "产品大类",
      subCategoryCode: "产品小类",
      customerCode: "客户代码",
      customerName: "客户名称",
      status: "销售订单状态",
      orderStatus: "订单状态",
      crsd: "离场期",
      crwd: '要求入库日期',
      deliveryDate: "交货期",
      CRAD: "CRAD",
      CRWD: "要求入库日期",
      qty: "订单数量",
      unitCode: "单位",
      unitName: '单位',
      division: "服装类别",
      productDivision: "分类",
      salesOrganization: "销售组织",
      season: "季度款",
      seasonDesc: "季度款描述",
      seasonal: '季节性',
      brandCode: '品牌',
      customerDivision: '客户部门',
      componentPack: '套装标识',
      orderOutsource: "外协标识",
      outsourceVendor: "外协供应商",
      prdProcess: "外协工段",
      outsourceQty: "外协数量",
      outsourceStartDate: "外协开始日期",
      outsourceEndDate: "外协结束日期",
      company:'公司',
      // 订单行数据
      soItem: '销售订单行号',
      itemStatus: '状态',
      projectionNo: '预测订单',
      projectionItemNo: '预测订单行号',
      itemNo: '关联订单行号',
      crystalStyleNo: 'Crystal款号',
      originalCustomerStyleNo: '原客户款号',
      customerStyleNo: '客户款号',
      factoryStyleNo: '本厂款号',
      customerPo: '客户PO',
      patternNo: '花型',
      materialCode: '物料编码',
      materialName: '物料名称',
      priorityType: '订单紧急度',
      country: '走货国家',
      area: '走货区域',
      productionVersion: '生产版本',
      routing: '工艺路线',
      routingVersion: '工艺路线版本',
      firstyarnDate: '纱线开始日期',
      fullyarnDate: '纱线结束日期',
      fbBodyStartDate: '关键物料到货开始日期',
      fbBodyEndDate: '关键物料到货结束日期',
      specialProcess: '特殊工艺',
      specialRemarks: '特殊工艺备注',
      specialAccessory: '特殊辅料',
      tolerance: '订单超量',
      isSantoni: '是否针织',
      buyMonth: '购买月',
      jobGroup: 'job group',
      isWashing: '是否洗水',
      isHt: '是否烫唛',
      sizeGroup: '尺码组',
      programNo: '客户项目号',
      customerProjectNumberTwo: '客户项目号2',
      gaugeGroup: '针的类型',
      confirmGg: 'gg明细针数',
      KnittingSam: 'Knitting Sam',
      LinkingSam: 'Linking Sam',
      SewingSam: 'Sewing Sam',
      BondingSam: 'Bonding sam',
      OfflineSeamsealSam: 'Offline Seamseal sam',
      printingFtyCode: '印花工厂编码',
      printingFty: '印花工厂名称',
      embFtyCode: '绣花工厂编码',
      embFty: '绣花工厂名称',

      // 订单行明细数据
      subItem: '销售订单子行号',
      subItemStatus: '状态',
      BomVersion: 'BOM版本',
      color: '颜色编码',
      colorName: '颜色名称',
      size: '尺码编码',
      sizeName: '尺码名称',
      // 外协操作
      soOutsourceOption: '订单外协操作',
      isOutsource: '是否外协',
      
    },
    tabPane: {
      orderMasterData: '销售订单',
      orderLineData: '销售订单行数据',
      orderLineDetailData: '销售订单行明细数据',
      status1: '下发',
      status2: '关闭',
      status3: '取消',
    },
    tab: {
      first: '基础数据',
      second: '自定义字段'
    },
    placeholder: {
      // 订单数据
      company:'请输入公司',
      customerProjectNumberTwo: '请输入客户项目号2',
      siteCode: "请选择工厂编码",
      so: "请输入销售订单",
      color: '请输入颜色编码',
      orderType: "请选择订单类型",
      series: "请输入系列",
      productFamilyCode: "请选择产品大类",
      subCategoryCode: "请选择产品小类",
      customerCode: "请选择客户代码",
      customerName: "请选择客户名称",
      status: "请选择销售订单状态",
      orderStatus: "请选择订单状态",
      crsd: "请选择离场期",
      crwd: '请选择要求入库日期',
      CRAD: "请选择CRAD",
      CRWD: "请选择要求入库日期",
      qty: "请输入订单数量",
      unitCode: "请选择单位",
      unitName: '请选择单位',
      division: "请选择服装类别",
      productDivision: "请选择分类",
      salesOrganization: "请输入销售组织",
      season: "请输入季度款",
      seasonDesc: "请输入季度款描述",
      seasonal: '请选择季节性',
      brandCode: '请输入品牌',
      customerDivision: '请输入客户部门',
      componentPack: '请输入套装标识',
      orderOutsource: "请选择外协标识",
      outsourceVendor: "请选择外协供应商",
      prdProcess: "请选择外协工段",
      outsourceQty: "请输入外协数量",
      outsourceStartDate: "请选择外协开始日期",
      outsourceEndDate: "请选择外协结束日期",
      // 订单行数据
      soItem: '请输入销售订单行号',
      itemStatus: '请选择状态',
      projectionNo: '请输入预测订单',
      projectionItemNo: '请输入预测订单行号',
      itemNo: '请输入关联订单行号',
      crystalStyleNo: '请输入Crystal款号',
      originalCustomerStyleNo: '请输入原客户款号',
      customerStyleNo: '请输入客户款号',
      factoryStyleNo: '请输入本厂款号',
      customerPo: '请输入客户PO',
      patternNo: '请输入花型',
      materialCode: '请选择物料编码',
      materialName: '物料名称',
      priorityType: '请选择订单紧急度',
      country: '请选择走货国家',
      area: '请选择走货区域',
      productionVersion: '请输入生产版本',
      routing: '请选择工艺路线',
      routingVersion: '请选择工艺路线版本',
      firstyarnDate: '请选择纱线开始日期',
      fullyarnDate: '请选择纱线结束日期',
      fbBodyStartDate: '请选择关键物料到货开始日期',
      fbBodyEndDate: '请选择关键物料到货结束日期',
      specialProcess: '请输入特殊工艺',
      specialRemarks: '请输入特殊工艺备注',
      specialAccessory: '请输入特殊辅料',
      tolerance: '请输入订单超量',
      isSantoni: '请选择是否针织',
      buyMonth: '请选择购买月',
      jobGroup: '请输入job group',
      isWashing: '请选择是否洗水',
      isHt: '请选择是否烫唛',
      sizeGroup: '请输入尺码组',
      programNo: '请输入客户项目号',
      gaugeGroup: '请输入针的类型',
      confirmGg: '请输入gg明细针数',
      KnittingSam: '请输入Knitting Sam',
      LinkingSam: '请输入Linking Sam',
      SewingSam: '请输入Sewing Sam',
      BondingSam: '请输入Bonding sam',
      OfflineSeamsealSam: '请输入Offline Seamseal sam',
      printingFtyCode: '请输入印花工厂编码',
      printingFty: '请输入印花工厂名称',
      embFtyCode: '请输入绣花工厂编码',
      embFty: '请输入绣花工厂名称',

      // 订单行明细数据
      subItem: '请输入销售订单子行号',
      subItemStatus: '请选择状态',
      BomVersion: '请选择BOM版本',
      colourCode: '请选择颜色编码',
      colorName: '请选择颜色名称',
      size: '请选择尺码编码',
      sizeName: '请选择尺码名称',
    },
    message: {
      orderOut: '外协成功',
      startData:"开始时间不能大于结束时间！",
      endData:"结束时间不能小于开始时间！",
    }
  }
}