export default {
  pattern: {
    digitalRange: "数字范围:",
    integer: "应只包含([0-9]的整数)",
    integer50: "应只包含([1-50]的整数)",
    integerCheck: "应只包含整数",
    englishNumbersSymbol: "应只包含([A-Z,0-9,-,_])",
    chineseWEnglishNumbers: "应只包含([中文、英文、数字])",
    numbersCapital: "应只包含只能数字、大写字母、_",
    numbersCapitalChinese: "应只包含数字、大写字母、_、中文、/",
    letterNumberChinese: "应只包含（[A~Z,_,0~9,中文])",
    commaLetterNumber: "应只包含（[A~Z,_,0~9,])",
    englishAndNumbers: "应只包含([英文、数字])",
    zeroNine: "应只包含[0-99]",
    englishNumberBias: "应只包含[英文、数字、— 、/]",
    englishNumberLine: "应只包含[英文、数字、— 、_]",
    phoneNumber: "应只包含数字,-",
    azNumberUnderline: "应只包含([A-Z,0-9,_,-,/])",
    letterSymbolNumber: "应只包含数字和英文字母和-,/",
    greaterThanZero: "应只包含大于0的整数",
    greaterThanZero1: "应只包含大于0的整数,且首位不能为0",
    letterSymbolNumber2: "应只包含数字和英文字母和-",
    letterSymbolNumber3: "应只包含数字和英文字母",
    decimalPointAndNumbers: "应只包含数字和小数点",
    englishAndNumbersPoint: "应只包含([英文、数字、.]",
    onlyContain: '只包含',
    positiveNumber: '应只含正数',
    positiveNumber1: '必须为小于或等于1的正数 ',
  }
}
