export default{
    //计划调整
    planChange:{
        title: "计划调整",//导出文件名
        label:{
            "workCode":"工作代码",
            "parentWorkCode":"父级工作代码",
            "itemNo":"工序序号",
            "processCode":"工序代码",
            "processName":"工序名称",
            "workDescribe":"工作描述",
            "workUserEst":"用户指定最早开始时间",
            "workUserLet":"用户指定最迟结束时间",
            "workUserMainResource":"用户指定主资源",
            "workTimeFixedFlag":"时间固定标识",
            "workResourceFixedFlag":"资源固定标识",
            "workStatusName":"工作状态",
            "workName":"工作描述",
            "searchError":"请选择排程任务和排程任务版本",
        },
        placeholder:{
            "workCode":"请输入工作代码",
            "workDescribe":"请输入工作描述",
            "workUserMainResource":"请检索用户指定主资源",
            "scheduleTaskCode":"请输入模板编号",
            "parentWorkCode":"请输入父级工作代码",
            "itemNo":"请输入工序序号",
            "processCode":"请输入工序代码",
            "processName":"请输入工序名称",
            "workUserEst":"请选择用户指定最早开始时间",
            "workUserLet":"请选择用户指定最迟结束时间",
            "workTimeFixedFlag":"请选择时间固定标识",
            "workResourceFixedFlag":"请选择资源固定标识",
            "workStatusName":"请选择工作状态",
            "workName":"请输入工作描述",
        },
        dialog:{
            //dialog
            "dialogTitle":"计划调整编辑",
            "batchDialogTitle":"计划调整批量编辑",
        },   
        options:{
            //markOptions
            "immobilization":"固定",
            "notImmobilization":"非固定",
            //resourcesDialog
            "materialType":"物料大类",
            "vendorName":"供应商名称",
            //placeholder
            "materialTypePlaceholder":"请输入物料大类",
            "vendorNamePlaceholder":"请输入供应商名称",
            //物料检索table
            "materialSpec":"物料规格",
            "materialCategory":"物料类别",
            "vendorCode":"供应商代码",
        }  
    },
}