export default {
  processRoute: {
    title: "工艺路线",
    subTitle: "工艺路线编辑",
    subTitleTitle: '工艺路线参数维护',
    subDetailTitle: '工艺路详情',
    label: {
      // siteCode:"工厂名称",
      // materialCode:"物料编码",
      materialName: "物料名称",
      // routingCode:"工艺路线",
      // routingDesc:"工艺路线说明",
      status: "状态",
      schedulingModel: "排程模型",
      remark: "备注",

      // itemNo:"序号",
      processId: "工序号",
      // workingHours:"制造时间",
      workingHoursUnitId: "制造时间单位",

      resourceForm: '资源类型',
      resourceMark: '资源识别码',
      resourceGroupId: '资源组编号',
      resourceGroupName: '资源组名称',
      resourceId: '资源编码',
      resourceName: '资源名称',
      forwardSettime: '前设置',
      forwardSettimeUnitId: '前设置单位',
      resourceAppointNumber: '资源选定编号',
      afterSettime: '后设置',
      afterSettimeUnitId: '后设置单位',
      timeConstraintMax: '移动时间MAX',
      timeConstraintMin: '移动时间MIN',
      timeConstraintUnitId: '移动时间单位',
      timeConstraintMethod: '接续方法',
      timeConstraintMethodLotMin: '接续批量',
      priority: '资源优先度',
      productionFactor: '制造效率',
      resourceQty: '必要资源量',
      features: 'features',
      patternNo: '花型',


      siteCode: "工厂名称",
      routingCode: "工艺路线",
      routingDesc: "工艺路线说明",
      version: "版本",
      customStyleNo: "客户款号",
      factoryStyleNo: "本厂款号",

      prdProcessSeq: '工段执行顺序',
      prdProcess: '工段',
      operationType: '工序类型',
      itemNo: '工序号',
      nextItemNo: '下一工序号',
      combinePart: '组合幅位',
      partCode: '幅位',
      componentCode: '部位',
      processCode: '工序代码',
      processName: '工序名称',
      apsCollobrationPlanning: '计算APS Collobration Planning',
      operationLevel: '工序等级',
      cmFlag: '是否车缝',
      machineType: '机器类型',
      materialCode: '物料',
      tool: '工具',
      workingHours: '制造时间',
      workingHoursUnitCode: '单位',
      targetProduction: '目标产量(10H)',
      pnPtm: 'PN PTM',
      bulkPtm: '大货PTM',
      processSort: '工序分类',
      bodyPart: '衣身部位',
      garmentComponent: '套装',
      effectiveFrom: '有效期起',
      effectiveTo: '有效期止',
      stageCode: '工艺路线阶段',
      entryFlag: '首工序标识',
      seq: '工段内排序',

    },
    placeholder: {
      // siteCode:"请选择工厂名称",
      // materialCode:"请选择物料编码",
      materialName: "请输入物料名称",
      // routingCode:"请输入工艺路线",
      // routingDesc:"请输入工艺路线说明",
      status: "请选择状态",
      schedulingModel: "请选择排程模型",
      remark: "请输入备注",

      select: '请选择',
      input: '请输入',

      siteCode: "请选择工厂名称",
      routingCode: "请输入工艺路线",
      routingDesc: "请输入工艺路线说明",
      version: "请输入版本",
      customStyleNo: "请输入客户款号",
      factoryStyleNo: "请输入本厂款号",

      prdProcessSeq: '请输入工段执行顺序',
      prdProcess: '请选择工段',
      operationType: '请输入工序类型',
      itemNo: '请输入工序号',
      nextItemNo: '请输入下一工序号',
      combinePart: '请输入组合幅位',
      color: '请输入幅位',
      componentCode: '请输入部位',
      processCode: '请检索工序代码',
      processName: '请输入工序名称',
      apsCollobrationPlanning: '请选择计算APS Collobration Planning',
      operationLevel: '请输入工序等级',
      cmFlag: '请选择是否车缝是否车缝',
      machineType: '请输入机器类型',
      materialCode: '请输入物料',
      tool: '请输入工具',
      workingHours: '请输入制造时间',
      workingHoursUnitCode: '请选择单位',
      targetProduction: '请输入目标产量(10H)',
      pnPtm: '请输入PN PTM',
      bulkPtm: '请输入大货PTM',
      processSort: '请输入工序分类',
      bodyPart: '请选择衣身部位',
      garmentComponent: '请输入套装',
      effectiveFrom: '请选择有效期起',
      effectiveTo: '请选择有效期止',
      stageCode: '请选择工艺路线阶段',
      entryFlag: '请选择首工序标识',
      features:'请输入features',
      patternNo: '请输入花型',
      seq: '请输入工段内排序',
    },
    rules: {
      resourceMark: "资源识别码不能为空",
      tabelrule: '请将表格填写完整！',
      siteId: '请选择工厂名称',
      agenName: "请选择代理商",
      tenantCode: "租户编码不能为空",
      tenantName: "租户名称不能为空",
      userName: "租户管理员账号不能为空",
      password: "租户商管理员密码不能为空",
      agentStatus: "帐号状态不能为空",
      startTime: "生效日期不能为空",
      endTime: "失效日期不能为空",
      telephone: "请正确填写电话号码",
      email: "请正确填写邮箱",
      resourceForm: '请选择资源类型',
      workingHoursUnitId: '请选择制造时间单位',
      forwardSettimeUnitId: '请选择前设置单位',
      afterSettimeUnitId: '请选择制后设置单位',
      resourceId: '请选择资源组编号或资源编码',
      // workingHours:'请输入制造时间',
      forwardSettime: '至少填写一个时间，单位',
      resourceCode: '请选择资源编码',
      resourceName: '请选择资源名称',
      timeConstraintUnitId: '请选择移动时间单位',
      resourceGroupName: '请输入正确资源组编号',
      resourceCodeTrue: '请输入正确资源编码',
      positiveInteger: '请输入正整数',


      siteCode: "请选择工厂名称",
      routingCode: "请输入工艺路线",
      routingDesc: "请输入工艺路线说明",
      version: "请输入版本",
      customStyleNo: "请输入客户款号",
      factoryStyleNo: "请输入本厂款号",
      prdProcessSeq: '请输入工段执行顺序',
      prdProcess: '请选择工段',
      operationType: '请输入工序类型',
      itemNo: '请输入工序号',
      nextItemNo: '请输入下一工序号',
      combinePart: '请输入组合幅位',
      color: '请输入幅位',
      componentCode: '请输入部位',
      processCode: '工序代码不存在, 请重新输入！',
      processName: '请输入工序名称',
      apsCollobrationPlanning: '请选择计算APS Collobration Planning',
      operationLevel: '请输入工序等级',
      cmFlag: '请选择是否车缝',
      machineType: '请输入机器类型',
      materialCode: '请输入物料',
      tool: '请输入工具',
      workingHours: '请输入制造时间',
      workingHoursUnitCode: '请选择单位',
      targetProduction: '请输入目标产量(10H)',
      pnPtm: '请输入PN PTM',
      bulkPtm: '请输入大货PTM',
      processSort: '请输入工序分类',
      bodyPart: '请选择衣身部位',
      row: '行数',
    },
  }
}