export default {
    //productionVersion
    productionVersion: {
        title: '生产版本',
        subTitle: '生产版本编辑',
        thirdTitle: '工艺路线物料参数维护',
        status: {
            cancel: '取消',
            plan: '计划中',
            release: '下达',
            product: '生产中',
            end: '结束'
        },
        options: {
            inputMaterial: "输入物料",
            outputMaterial: "输出物料",
        },
        label: { 
            material: "物料",
            process: "工序",
            productionVersionCode: "生产版本编号",
            productionVersionName: "生产版本名称",
            productionVersionDesc: "生产版本描述",
            materialCode: "物料编码",
            materialCodeChild: "物料编码",
            bomVersion: "BOM版本",
            routingCode: "工艺编号",
            minQuantity: "起始批量",
            maxQuantity: "截至批量",
            effectiveFrom: "生效日期",
            effectiveTo: "失效日期",
            processCode: "工序编号",
            workingHours: "制造时间",
            workingHoursUnitName: "制造时间单位",
            siteVaild: "请选择工厂名称",
            //维护跳转画面
            inputOrOutputMaterial: "输入或输出物料",
            materialMark: "物料识别码",
            usageRatio: "用量比例",
            preProcessNo: "前工序编号",
            timeConstraintMax: "移动时间MAX",
            timeConstraintMin: "移动时间MIN",
            timeConstraintUnit: "移动时间单位",
            timeConstraintMethod: "接续方法",
            scrapQty: "废品数量",
            passRate: "成品率",
            addRow:'新建行',
            deleteRow:'删除行',
        },
        placeholder: {
            productionVersionCode: "请输入生产版本编号",
            productionVersionName: "请输入生产版本名称",
            productionVersionDesc: "请输入生产版本描述",
            materialCode: "请输入物料编码",
            bom: "请输入BOM版本",
            routing: "请选择工艺编号",
            minQuantity: "请输入起始批量",
            maxQuantity: "请输入截至批量",
            effectiveFrom: "请选择生效日期",
            effectiveTo: "请选择失效日期",
            materialMarkPlaceholder: "请选择物料识别码",
            materialCodeChoosePlaceholder: "请选择物料编码",
            timeConstraintUnitPlaceholder: "请选择移动时间单位",
            timeConstraintMethodPlaceholder: "请选择接续方法",
        },
        ruler: {
            inputOrOutputMaterial: "请选择输入或输出物料",
            usageRatio: "请输入用量比例",
            usageRatioSaveCheckNumber: "用量比例最多填写10位数字且最多保留五位小数",
            scrapQty: "废品数量最多填写10位数字且最多保留五位小数",
            passRate: "成品率最多填写10位数字且最多保留五位小数",
            materialCode:"物料编码不存在,请重新输入",
            preProcessNo:"工序编号不存在，请重新输入",
        },
    }
}