export default {
  projectionNo: {
    title: '预测订单主数据',
    subTitle: '预测订单主数据新增',
    editTitle: '预测订单主数据编辑',
    label: {
      // 订单数据
      siteCode: "工厂编码",
      projectionNo: "预测订单",
      orderType: "订单类型",
      status: "订单状态",
      productionSiteCountry: "生产工厂国家",
      customerCode: "客户代码",
      customerName: "客户名称",
      crystalStyleNo: 'Crystal款号',
      originalCustomerStyleNo: '原客户款号',
      customerStyleNo: '客户款号',
      customerStyleDesc: '客户款号描述',
      series: "系列",
      productFamilyCode: "产品大类",
      subCategoryCode: "产品小类",
      salesOrganization: "销售组织",
      season: "季度款",
      seasonDesc: "季度款描述",
      seasonal: "季节性",
      division: "服装类别",
      productDivision: "分类",
      brandCode: '品牌',
      orderOutsource: "外协标识",
      outsourceVendor: "外协供应商",
      prdProcess: "外协工段",
      outsourceQty: "外协数量",
      outsourceStartDate: "外协开始日期",
      outsourceEndDate: "外协结束日期",
      // 预测订单行数据
      projectionItemNo: "预测订单行号",
      projectionOrderQty: "预测订单数量",
      projectionOrderUnitCode: "预测订单数量单位",
      salesOrder: "转销售订单",
      salesOrderItemNo: "销售订单行号",
      salesOrderQty: "销售订单数量",
      salesOrderUnitCode: "销售订单数量单位",
      salesOrderStatus: "销售订单状态",
      factoryStyleNo: '本厂款号',
      priorityType: "订单紧急度",
      patternNo: '花型',
      materialCode: '物料编码',
      materialName: '物料名称',
      crsd: '离厂期',
      crad: '要求抵达日期',
      componentPack:'齐套标识',
      shipCountry: '走货国家',
      shipMode: '运送模式',
      fbBodyShipMode: '主衫身运送模式',
      fbTrimDate: '下栏布期',
      fbTrimShipMode: '下栏运送模式',
      fbBodyStartDate: '关键物料到货开始日期',
      fbBodyEndDate: '关键物料到货结束日期',
      bdDate: 'BD日期',
      poDate: 'PO日期',
      fsoDate: 'FSO',
      dsoDate: 'DSO',
      majorYarnDesc: '纱线描述',
      firstyarnDate: '纱线开始日期',
      fullyarnDate: '纱线结束日期',
      mainYarnVendor: '纱线主要供应商',
      fabricDesc: '布',
      fabricRemarks: '布备注',
      fabricMill: '布厂',
      fabricMillCode: '布厂编码',

      programNo: '客户项目号',
      custProgramName1: '客户项目名称1',
      custProgramName2: '客户项目名称2',
      specialProcess: '特殊工艺',
      specialRemarks: '特殊工艺备注',
      gaugeGroup: '针的类型',
      machine: '机器类型',
      confirmGg: 'gg明细针数',
      itemRemark: 'Projection项目备注',
      KnittingSam: 'Knitting Sam',
      LinkingSam: 'Linking Sam',
      SewingSam: 'Sewing Sam',
      BondingSam: 'Bonding sam',
      OfflineSeamsealSam: 'Offline Seamseal sam',
      heatTransferLable: 'HT Label',
      washingType: '洗水类型',
      washingTypeDesc: '洗水类型描述',
      orderOutsource: "外协标识",
      printingFtyCode: "印花工厂编码",
      printingFty: "印花工厂名称",
      embFtyCode: "绣花工厂编码",
      embFty: "绣花工厂名称",
      // 外协操作
      soOutsourceOption: '订单外协操作',
      isOutsource: '是否外协',
    },
    tabPane: {
      projectionNoData: '预测订单',
      projectionNoLineData: '预测订单行数据',
    },
    tab: {
      first: '基础数据',
      second: '自定义字段'
    },
    placeholder: {
      // 订单数据
      siteCode: "请选择工厂编码",
      projectionNo: "请输入预测订单",
      series: "请选择系列",
      productFamilyCode: "请选择产品大类",
      subCategoryCode: "请选择产品小类",
      customerCode: "请选择客户代码",
      customerName: "请选择客户名称",
      orderType: "请选择订单类型",
      status: "请选择订单状态",
      productionSiteCountry: "请选择生产工厂国家",
      crystalStyleNo: '请输入Crystal款号',
      originalCustomerStyleNo: '请输入原客户款号',
      customerStyleNo: '请输入客户款号',
      customerStyleDesc: '请输入客户款号描述',
      division: "请选择服装类别",
      productDivision: "请选择分类",
      componentPack: "请输入齐套标识",
      salesOrganization: "请输入销售组织",
      season: "请输入季度款",
      seasonDesc: "请输入季度款描述",
      seasonal: "请选择季节性",
      orderOutsource: "请选择外协标识",
      outsourceVendor: "请选择外协供应商",
      prdProcess: "请选择外协工段",
      outsourceQty: "请输入外协数量",
      outsourceStartDate: "请选择外协开始日期",
      outsourceEndDate: "请选择外协结束日期",
      brandCode: '请输入品牌',
      // 预测订单行数据
      projectionItemNo: "请输入预测订单行号",
      projectionOrderQty: "请输入预测订单数量",
      projectionOrderUnitCode: "请选择预测订单数量单位",
      salesOrder: "请输入转销售订单",
      salesOrderItemNo: "请输入销售订单行号",
      salesOrderQty: "请输入销售订单数量",
      salesOrderUnitCode: "请选择销售订单数量单位",
      salesOrderStatus: "请选择销售订单状态",
      priorityType: "请选择订单紧急度",
      patternNo: '请输入花型',
      materialCode: '请选择物料编码',
      materialName: '请选择物料名称',
      crsd: '请选择离厂期',
      crad: '请选择要求抵达日期',
      shipCountry: '请选择走货国家',
      shipMode: '请选择运送模式',
      factoryStyleNo: '请输入本厂款号',
      fbBodyStartDate: '请选择关键物料到货开始日期',
      fbBodyEndDate: '请选择关键物料到货结束日期',
      bdDate: '请选择BD日期',
      poDate: '请选择PO日期',
      fsoDate: '请选择FSO',
      dsoDate: '请选择DSO',
      majorYarnDesc: '请输入纱线描述',
      firstyarnDate: '请选择纱线开始日期',
      fullyarnDate: '请选择纱线结束日期',
      mainYarnVendor: '请输入纱线主要供应商',
      fabricDesc: '请输入布',
      fabricRemarks: '请输入布备注',
      fabricMill: '请输入布厂',
      fabricMillCode: '请输入布厂编码',
      fbBodyShipMode: '请选择主衫身运送模式',
      fbTrimDate: '请选择下栏布期',
      fbTrimShipMode: '请选择下栏运送模式',
      programNo: '请输入客户项目号',
      custProgramName1: '请输入客户项目名称1',
      custProgramName2: '请输入客户项目名称2',
      specialProcess: '请选择特殊工艺',
      specialRemarks: '请输入特殊工艺备注',
      gaugeGroup: '请输入针的类型',
      machine: '请输入机器类型',
      confirmGg: '请输入gg明细针数',
      itemRemark: '请输入Projection项目备注',
      KnittingSam: '请输入Knitting Sam',
      LinkingSam: '请输入Linking Sam',
      SewingSam: '请输入Sewing Sam',
      BondingSam: '请输入Bonding sam',
      OfflineSeamsealSam: '请输入Offline Seamseal sam',
      heatTransferLable: '请输入HT Label',
      washingType: '请输入洗水类型',
      washingTypeDesc: '请输入洗水类型描述',
      printingFtyCode: "请输入印花工厂编码",
      printingFty: "请输入印花工厂名称",
      embFtyCode: "请输入绣花工厂编码",
      embFty: "请输入绣花工厂名称",
    },
    message: {
      orderOut: '外协成功'
    }
  }
}