export default {
    //采购订单
    purchaseOrder: {
      title: '采购订单',
      subTitle: '采购订单编辑',
      importTitle: '采购订单导入',
      label: {
        "vendorCode":"供应商编码",
        "vendorName":"供应商名称",
        "purchaseOrder":"采购订单",
        "poItem":"行号",
        "materialCode":"物料编码",
        "materialName":"物料名称",
        "qty":"采购数量",
        "unit":'单位',
        "arrivedDate":"采购到货日期",
        "status":"状态",
        "siteName":"工厂名称",
        "siteCode":"工厂编码",
        po:'采购订单编号',
            deliveryDate:'交货日期',
            poType:'采购订单类型',
            pendingQty:'未清数量',
            salesOrder:'销售订单',
      },
      placeholder:{
        "vendorCode":"请输入供应商编码",
        "vendorName":"请输入供应商名称",  
        "purchaseOrder":"请输入采购订单",  
        "poItem":"请输入行号", 
        "materialCode":"请选择物料编码",
        "materialName":"请选择物料名称", 
        "qty":"请输入采购数量",
        "unit":'请选择单位',
        "arrivedDate":"请选择采购到货日期",
        "status":"请选择状态",
        "siteName":"请选择工厂名称",
        "siteCode":"请选择工厂编码",
        po:'请输入采购订单编号',
            deliveryDate:'交货日期',
            poType:'请输入采购订单类型',
            pendingQty:'请输入未清数量',
            salesOrder:'请输入销售订单',
      },
      rules:{
        "poItemNameBlur":'行号只能数字',
        "handleMaterialNameBlur":'物料名称不存在,请重新输入',
        "handleMaterialCodeBlur":'物料编码不存在,请重新输入',
        "handleVendorNameBlur":'供应商名称不存在,请重新输入',
        "handleVendorCodeBlur":'供应商编码不存在,请重新输入',
        "vendorCodePlaceholderNumber":'供应商编码只能数字和英文字母和-,/,—_',
        "materialCodePlaceholderNumber":'物料编码只能数字和英文字母和-,/,_'
      },
    }
  }