export default {
    //GR-收货管理
    receiving: {
      title: 'GR-收货管理',
      subTitle: 'GR-收货管理编辑',
      label: {
        "materialCode":"物料编码", 
        "materialName":"物料名称", 
        "inputQty":"入库数量", 
        "unitCode":"单位", 
        "materialCategory":"物料大类", 
        "materialSpec":"物料规格", 
        "productionOrder":"生产工单", 
        "warehousingEntry":"入库单据", 
        "lineNumber":"行号", 
        "receiver":"入库人员", 
        "createDate":"入库日期", 
        "workReportType":"报工类型", 
        "process":"制程段", 
        "whName":"仓库名称", 
        "whCode":"仓库代码", 
        "siteCode":"工厂", 
        "siteName":"工厂名称", 
        "stockLocCode":"库存地点", 
        "remark":"备注"
      },
      placeholder:{
        "productionOrder":"请选择生产工单",
        "materialCode":"请输入物料编码",
        "materialName":"请输入物料名称",
        "inputQty":"请输入入库数量",
        "unitCode":"请选择单位",
        "materialCategory":"请选择物料大类",
        "materialSpec":'请输入物料规格',
        "warehousingEntry":'请输入入库单据',
        "lineNumber":'请输入行号',
        "receiver":'请输入入库人员',
        "createDate":'请选择入库日期',
        "workReportType":'请选择报工类型',
        "process":'请选择制程段',
        "siteCode":'请选择工厂',
        "whName":'请选择仓库名称',
        "whCode":'请选择仓库代码',
        "stockLocCode":'请选择库存地点',
        "remark":'请输入备注',
      },
      rules:{
        "whCodePlaceholderNumber":"应只包含[英文、数字、— 、/]",
        "productionOrderPlaceholder":"应只包含（[英文、数字]）",
        "receiverPlaceholderNumber":"应只包含（[中文、英文、数字]）",
        "handleMoBlur":'生产工单不存在，请重新输入！',
        "handlewhCodeBlur":'仓库编码不存在，请重新输入！',
        "handleWhnameBlur":'仓库名称不存在，请重新输入！',
        "handleStockBlur":'库存地点不存在，请重新输入！',
      },
    }
  }