export default {
  resource: {
    title: "资源",
    subTitle: "资源新增",
    editTitle: "资源编辑",
    label: {
      resourceCode: "资源编码",
      resourceName: "资源名称",
      resourceGroupCode: "资源组",
      resourceType: "资源大类",
      resourceTypeDesc: "资源大类描述",
      resourceSubtype: "资源小类",
      locno: "车间",
      efficiency: "制造效率(%)",
      isEffective: "是否有效",
      inputHc: "投入人数",
      features: "生产特征特性",
      maxStorage: "资源量最大值",
      minStorage: "资源量最小值",
      idle: "idle(%)",
      //add edit form
      customer: "客户",
      category: "品类",
      specialProcess: "特殊工艺",
      priority: "优先级",
      numberOfResources: "资源数量",
      attendance: "出勤率(%)",
      prdProcess: "工段",
      prdProcessName: "工段",
      machineInch: "机寸号",
      needleNum: "针数",
      assetType: "资产类型",
      location: "位置",
      screenQty: "网板数量",
      rentStartTime: "租用开始时间",
      rentEndTime: "租用结束时间",

      fixedAssetsCode: "固定资产编号",
      assetsCode: "设备编号",
      resourceVendor: "设备供应商",
      stopStartTime: "资源停机开始时间",
      stopMinutes: "预计停机时长",
      matchOh: "是否有过热机",
      scenarioType: "场景类型",
      volume: "容量",
      resourceCategory: "资源类别",
      shift: "班次",
      schedulingModel:"排程模型",
      displaySequence:"显示顺序",
      
    },
    tab: {
      first: "基础数据",
      second: "自定义字段",
      third: "资源组别",
    },
    options: {
      first: "主资源",
      second: "副资源",
    },
    placeholder: {
      idle: "请输入idle",
      integerVaild: "请输入整数",
      //placeholder
      resourceCode: "请输入资源编码",
      resourceName: "请输入资源名称",
      basicAttribute: "基础属性",
      resourceGroupCode: "请选择资源组",
      resourceType: "请选择资源大类",
      resourceTypeDesc: "请选择资源大类描述",
      resourceSubtype: "请选择资源小类",
      locno: "请选择车间",
      efficiency: "请输入制造效率",
      isEffective: "请选择是否有效",
      inputHc: "请输入投入人数",
      machineInch: "请输入机寸号",
      needleNum: "请输入针数",
      parameterAttribute: "参数类属性",
      limitedPlan: "请选择有限计划",
      limitedCapacity: "请选择有限能力",
      features: "请选择生产特征特性",
      schedulingModel: "请选择排程场景",
      expressionProperty: "表达式类属性",
      customerCode: "请选择客户代码",
      numberOfResources: "请输入资源数量",
      attendance: "请输入出勤率",
      prdProcess: "请选择工段",
      assetType: "请选择资产类型",
      location: "请输入位置",
      screenQty: "请输入网板数量",
      rentStartTime: "请选择租用开始时间",
      rentEndTime: "请选择租用结束时间",
  
      fixedAssetsCode: "请输入固定资产编号",
      assetsCode: "请输入设备编号",
      resourceVendor: "请选择设备供应商",
      stopStartTime: "请选择资源停机开始时间",
      stopMinutes: "请输入预计停机时长",
      matchOh: "请选择是否有过热机",
      maxStorage: "请输入资源量最大值",
      minStorage: "请输入资源量最小值",
      scenarioType: "请选择场景类型",
      volume: "请输入容量",
      shift: "请选择班次",
      resourceCategory: "请输入资源类别",
      tabelrule: "请维护资源组别",
      displaySequence: "请输入显示顺序",
      attendanceRate: "请输入出勤率",
    },
  },
};
