export default {
    //销售订单
    salesOrder: {
      title: '销售订单',
      subTitle:'销售订单编辑',
      label: {
        "so":"销售订单号",
        "soItem":"销售订单行号",
        "productType":"产品类型",
        "orderType":"订单类型",
        "productFamilyCode":"产品族",
        "materialCode":"物料编码",
        "materialName":"物料名称",
        "customerName":"客户名称",
        "color":"颜色",
        "shipEarly":"是否可提前发货",
        "priorityCode":"Priority CODE",
        "crsd":"CRSD",
        "crad":"CRAD",
        "crwd":"要求入库日期",
        "status":"状态",
        "qty":"订单数量",
        "unitName":"单位",
      },
      placeholder:{
        "so":"请输入销售订单号",
        "soItem":"请输入销售订单行号",
        "productType":"请选择产品类型",
        "orderType":"请选择订单类型",
        "productFamilyCode":"请选择产品族",
        "materialCode":"请选择物料编码",
        "materialName":"请选择物料名称",
        "customerName":"请选择客户名称",
        "color":"请选择颜色",
        "shipEarly":"请选择是否可提前发货",
        "priorityCode":"请选择Priority CODE",
        "crsd":"请选择CRSD",
        "crad":"请选择CRAD",
        "crwd":"请选择要求入库日期",
        "status":"请选择状态",
        "qty":"请输入订单数量",
        "unitName":"请选择单位",
      },
      rules:{
        "qtyRule":'数字范围:0-9999999999999999',
        "soRule":'只能数字和英文字母和-，_,#',
      },
    }
  }