export default {
    schedulingOrder:{
        label: {
            "siteName":"工厂名称",
            "materialCode":"物料编码",
            "unitId":"单位",
            "scheduleOrder":"排程订单",
            "orderType":"订单类型",
            "qty":"订单数量",
            "planReleaseDate":"计划下达日期",
            "expectKittingDate":"预计齐套日期",
            "planStartDate":"计划开始日期",
            "planFinishDate":"计划完成日期",
            "deliveryDate":"交货期",
            "priority":"订单优先级",
            "so":"销售订单",
            "soItem":"销售订单行号",
            "earlyStartTime":"最早开始时间",
            "lateStartTime":"最晚开始时间",
            "earlyEndTime":"最早结束时间",
            "lateEndTime":"最晚结束时间",
            "customer":"客户",
            "vendor":"供应商",
            "dispatchFlag":"分派标志",
            "orderSpec1":"规格1",
            "orderSpec2":"规格2",
            "orderSpec3":"规格3",
            "orderSpec4":"规格4",
            "orderStatus":"订单状态",
            "orderrGroup":"订单组",
            "leadTime":"交货提前期",
            "manufacturingEfficiency":"制造效率",
            "actualResultsQty":"实绩数量",
            "actualResultsTime":"实绩取得时刻",
            "childOrder":"子订单",
            "parentOrder":"父订单",
            "schedulingModel":"排程模型",
            "productionVersion":"生产版本编号",
            "selfBuildFlag":"自建标识",
            "rangeSpec1": "范围特征1",
            "rangeSpec2": "范围特征2",
            "customerId":"客户",
            "customerName":"客户",
            "orderAssignmentDirection":"分派方向",
            "exportTitle":"排程订单",
            "exportTitlePcrwbb":"排程任务版本",
        },
        placeholder: {
            "orderAssignmentDirection":"请选择分派方向",
            "siteName":"请选择工厂名称",
            "materialCode":"请输入物料编码",
            "unitId":"请选择单位",
            "scheduleOrder":"请输入排程订单",
            "orderType":"请选择订单类型",
            "qty":"请输入订单数量",
            "planReleaseDate":"请选择计划下达日期",
            "expectKittingDate":"请选择预计齐套日期",
            "planStartDate":"请选择计划开始日期",
            "planFinishDate":"请选择计划完成日期",
            "deliveryDate":"请选择交货期",
            "priority":"请输入订单优先级",
            "so":"请输入销售订单",
            "soItem":"请输入销售订单行号",
            "earlyStartTime":"请选择最早开始时间",
            "lateStartTime":"请选择最晚开始时间",
            "earlyEndTime":"请选择最早结束时间",
            "lateEndTime":"请选择最晚结束时间",
            "customer": "请输入客户",
            "specialCustomer":"请检索客户信息",
            "vendor":"请输入供应商",
            "dispatchFlag":"请选择分派标志",
            "orderSpec1":"请选择规格1",
            "orderSpec2":"请选择规格2",
            "orderSpec3":"请选择规格3",
            "orderSpec4":"请选择规格4",
            "orderStatus":"请选择订单状态",
            "orderrGroup":"请输入订单组",
            "leadTime":"请输入交货提前期",
            "manufacturingEfficiency":"请输入制造效率",
            "actualResultsQty":"请输入实绩数量",
            "actualResultsTime":"请输入实绩取得时刻",
            "childOrder":"请输入子订单",
            "parentOrder":"请输入父订单",
            "schedulingModel":"请选择排程模型",
            "productionVersion":"请选择生产版本编号",
            "selfBuildFlag":"请选择自建标识",
            "rangeSpec1": "请输入范围特征1",
            "rangeSpec2": "请输入范围特征2",
            "customerId":"客户",
            "customerName":"客户",
        }
    },
    
}