export default {
  //排产工艺路线
  scheduleRouting: {
    title: "排产工艺路线",
    subTitle1: " 工艺明细",
    subTitle2: "副资源需求",
    label: {
      styleNo: "款号",
      version: "工艺路线版本",
      similarStyle: "相似款号",
      stageCode: "工艺路线阶段",
      patternNo: "花型",
      specialProcess: "特殊工艺",
      basicProcess: "基础工艺",
      newAndOldStyles: "新旧款",
      wingType: "侧翼类型",
      markeType: "唛头类型",
      glueType: "点胶类型",
      garmentComponent: "套装标识",
      effectiveFrom: "有效期起",
      effectiveTo: "有效期止",
      itemType1:"前工序",
      itemType2:"后工序",
      item: {
        itemNo: "工序编号",
        itemType: "前后工序",
        prdProcess: "所属工段",
        partCode: "幅位编码",
        partName: "幅位名称",
        componentCode: "部位编号",
        componentName: "部位名称",
        componentStyle: "部件款号",
        nextItemNo: "下一工序编号",
        processQty: "加工数量",
        workingHours: "标工(min)",
        unitTimeOutput: "单位时间产出(h)",
      },
      resource: {
        itemNo: "工序编号",
        prdProcess: "工段",
        componentName: "部位",
        resourceCode: "副资源编号",
        resourceName: "副资源名称",
        resourceQty: "副资源数量",
      },
    },
    placeholder: {},
    rules: {},
    optionLabel: {},
  },
};
