export default {
  singleTable: {
    title: "对单表",
    subtitle: "物料齐套详情",

    label: {
      orderCode: "订单号",
      queryDimension: "查询维度",
      combination: "组合维度",
      sku: "SKU维度",
      orderStatus: "订单状态",
      open: "打开",
      close: "关闭",
      department: "部门",
      po: "PO码",
      dischargeQuantity: "排料数",
      productionResponsePeriod: "生产回复期",
      ingredients: "主料",
      procurementLeadTime: "采购复期",
      auxiliaryMaterials: "辅料",
      packagingMaterials: "包材",
      workShopCode: "生产车间",
      specialProcess: "特殊工艺",
      sprintingProcess: "丝印工艺",
      category: "品类",
      model: "新/旧款",
      isCup: "有/无棉杯",
      wingType: "侧翼类型",

      standardWorker: "标工",
      workPoint: "工分",
      schedulingMonth: "排料月份",
      dischargeInterval: "排料区间",
      monthCustomerPeriod: "客期的月份",
      customerPeriodInterval: "客期区间",
      customerWeek: "客期周",
      readyWearCycle: "成衣周期",
      orderChangeRecord: "订单变更记录",
      orderQuery: "订单查询",
    },

    placeholder: {},
  },
};
