export default {
    sopCommon:{
        planStory:'计划故事',
        description:'描述',
        model:"模型",
        status:'状态',
        status0:'未激活',
        status1:'已激活',
        status2:'失效',
        storageTimeLevel:'时间计划层级',
        timeFrame:'时间范围',
        copy:"复制",
        confirmed:"确认",
        versionName:"版本名称",
        operationSet:"运算功能配置",
        planModel:'计划模型',
        planView:'计划视图',
        version:"版本",
        operation:"运算功能",
        operatorType:"运算类型",
        frontMode:"前台模式",
        backendMode:"后台模式",
        timeLevel: "时间层级",
        addition: "添加",
        dimension: "维度",
        measure: "度量",
        aggregationMode: "聚合模式",
        tips: "提示",
        screen: "筛选",
        allItem: "全部项",
        chooseItem: "已选择项",
        search: "搜索",
        storyVersion: "故事版本",
        details: "详情",
        createTime: "创建时间",
        updateTime: "修改时间",
        type: "类型",
        priorityType: "类别",
        userName: "用户名",
        fullName: "用户姓名",
        employeeNo: "员工编号",
        roleName: "角色名称",
        roleDescription: "角色描述",
        user: "用户",
        role: "角色",
        time: "时间",
        data:"数据",
        universal:"通用",
        designation:"名称",
        attribute:"属性",
        attributeName:"属性名称",
        attributeType:"属性数据类型",
        modelName:"模型名称",
        allField:"全部字段",
        choosedField:"已选择字段",
        unhandled: "未处理",
        processed: "已处理",
        hasBeenSent: "已发送",
        main:"主要",
        scene: "场景",
        story: "故事",
        reName: "重命名",
        modelRelation: "模型关联",
        chooseModel: "选择模型",
        associatedDimension: "已关联的维度",
        addLink:"添加关联",
        productcode:"产品编码",
        productname:"产品名称",
    },
    sopMessageCommon:{
        storyName:"请输入计划故事名称",
        targeStoryName:"请输入目标计划故事名称",
        description:"请输入描述",
        status:"请选择状态",
        storageTimeLevel:"请选择时间计划层级",
        dateCompare:"开始时间不能大于结束时间",
        inputType:'不允许输入下划线 " _ " 横线 " - " 以外的符号!',
        time:"请选择时间范围",
        versionId:"请选择复制版本",
        versionName:"请输入版本名称",
        startDate:"请选择开始时间",
        endDate:"请选择结束时间",
        measureIdMsg:"请选择度量",
        dimensionMsg:"请选择维度",
        aggregateTypeModel:"请选择聚合模式",
        fieldMsg:'请选择字段',
        storyTimeLevelMsgStart: "请先选择比计划故事设定的【",
        storyTimeLevelMsgEnd: "层级范围",
        storyTimeLevelHigherMsg: "】相等或更高的",
        storyTimeLevelLowMsg: "】相等或更小的",
        chooseTimeLevelAddMsg: "请选择时间维度累计层级",
        timeLevelMsgStart: "请先选择比时间层级设定的【",
        timeLevelNotNullMsg: "请选择时间计划层级",
        tableOrViewNotNullMsg: "请选择表 / 视图",
        modelNotNullMsg: "请选择模型",
        dateDimensionNotNullMsg: "请选择时间维度",
        dimensionOrMeasureDeleteNotAllowed: "当前模型的维度或度量字段已在警告规则中使用,不允许删除！",
        measureDeleteNotAllowed: "当前度量字段已在警告规则中使用,不允许删除！",
        dimensionDeleteNotAllowed: "当前维度字段已在警告规则中使用,不允许删除！",
        chooseOneDimension: "至少维护一个维度",
        chooseOneMeasure: "至少维护一个度量",
        operationSucceeded: "操作成功",
        operationFailed: "操作失败,请联系管理员",
        dataRestoreMsg: "已修改的数据在重置后将被还原，是否继续重置？",
        cancelReset: "已取消重置",
        choosePlanningStroy: "请先选择计划故事",
        timeLevelNotNull: "请先选择时间层级",
        chooseActivityResources: "请选择活动资源",
        maintainASetOfDataMsg: "至少维护一组数据",
        maintainOneRuleGroupMeasureMsg: "规则组至少维护一组度量",
        improveInformationMsg: "请完善度量规则信息",
        noChooseRuleGroupMsg: "警告规则未选择",
        inputWarnningRuleNameMsg: "请输入警告规则名称",
        chooseDataSourceTypeMsg: "请选择数据源类型",
        chooseSeverityMsg:"请选择严重度",
        chooseStroyMsg: "请选择计划故事",
        chooseStroyVersionMsg: "请选择故事版本",
        targetWarnningRuleNameNotNullMsg: "请输入目标警告规则名称",
        singleCopyMsg: "计划故事复制只能单条复制",
        notActiveWarnRuleNotRunMsg: "未激活的警告规则不能运行",
        activeRuleMaintainMsg: "激活规则需要先维护",
        priorityTypeMsg:"请选择类别",
        dimensionName:"请输入维度名称",
        dimensionProName:"请输入维度产品名称",
        num6: '输入数值，小数不超过6位。',
        activeToDelete:"激活列表中的复选框来启用删除",
        attributeName: "请输入属性名称",
        attributeType:"请选择属性数据类型",
        revPlaceholder:"请选择版本",
        uploadFail:"上传失败，请重新上传",
        uploadFile:"请选择上传文件",
        chooseDeleteModelMsg:"请选择要删除的模型！",
        deleteModelMsg:"是否删除模型Model",
        andModelData:"以及其数据？",
        chooseDeleteDimensionMsg:"请选择要删除的公用维度！",
        deleteDimensionMsg:"是否删除模型公用维度",
        copyModelMsg:"请选择要复制的模型(Model)！",
        oneModelMsg:"请选择同一计划故事下的计划模型",
        inputModel:"请输入模型名称",
        polymerizationType:"请选择聚合模式",
        decompose:"请选择分解模式",
        typeMsg:"请选择类型",
        valueMsg:"请选择值",
        decimalMsg:'请选择小数点位数',
        measureName:"请输入度量名称",
        isEditMsg:"请选择是否可编辑",
        disaggregateFormula:"选择 【按比例，否则平均】或者【按比例，否则复制时】，分解公式不能为空",
        unitType:"单位/货币 类型",
        unitValue:"单位/货币 值",
        formatDigit:"小数位数",
        DimensionAdd:"添加Dimension，数据会被清空，是否继续？",
        DimensionAddTitle:"提示：添加会清除已导入的数据，请提前下载",
        DimensionDelete:"是否删除Dimension：",
        DimensionDeleteTitle:"提示：删除会清除已导入的数据，请提前下载",
        deleteDimensionAttribute:"是否确认删除属性",
        sheetMsg:"输入标签名称",
        lowerLimit:'请输入下限',
        upperLimit:"请输入上限",
        lowUpperLimit:"数据有重叠，不可小于上一行的上限值",
        centerUpperLimit:"数据有重叠，上下限值符号选择<=时，上下限值不可相等",
        upperUpperLimit:"数据有重叠，不可大于上限值",
        upperLowerLimit:"数据有重叠，不可大于下一行的下限值",
        lowLowerLimit:'数据有重叠，不可小于下限值',
        chooseLocationCategory: "请选择位置类别",
        chooseLocationMsg: "请选择位置",
        chooseLocationFromCategoryMsg: "请选择供应源位置类别",
        chooseLocationFromMsg: "请选择供应源位置",
        chooseEffectiveMsg: "请选择是否有效",
        inputPositiveIntegerMsg: "请输入正整数",
        zeroOneNumberMsg: "请输入0-1之间的数值（包括0和1）",
        chooseLeadTimeMsg: "请选择提前期",
        integerVaild: "请输入整数",
        timeIntervalOverlapMsg: "时间区间不允许重叠",
        inputTimeIntervalMsg: "请维护没有填写的时间区间",
        locationOrLocationFormMsg: "产品与产品族至少输入一个",
        inputStartTimeMsg: "请填写的开始时间",
        inputProductSourceNameMsg: "请输入生产源名称",
        inputProductSourceDescMsg: "请输入生产源描述",
        chooseFactoryMsg: "请选择工厂",
        notChooseProductAndProductFamilyMsg: "请不要同时选择产品族和产品",
        chooseProductOrProductFamilyMsg: "请选择产品族或产品",
        objectCategoryNotNullMsg: "请选择对象类别",
        chooseObjectValueMsg: "请选择对象值",
        inputCalendarNameMsg: "请输入日历名称",
        updateMsg: "是否放弃当前页签的所有修改?",
        pleaseAssociatedDimension: "请关联一个维度",
        chooseModelDimension: "请选择一个模型的维度完成匹配！",
        chooseOtherModelDimension: "请选择另一个模型的维度完成匹配！",
        differentModelMsg: "两个Model不能为同一个",
        dimensionAssociatedSuccessMsg: "当前维度已完成，可以增加维度继续关联",
        calendarDataRefreshMsg: "是否从日历数据重新拉取日历进行覆盖?",
        inputScenarioNameMsg: "请输入场景名称",
        chooseSaveSceneMsg: "请选择保存为场景",
        inputViewNameMsg: "请输入计划视图名称",
        chooseTimeLevelMsg: "请选择时间层级",
        dataNotActiveMsg: "当前数据未激活，无法维护",
        chooseDataMsg: "请先选择数据",
        activeOrNotMsg: "是否激活?",
        invalidOrNotMsg: "是否失效?",
        cannotSaveMsg: "暂无编辑的数据，无法保存",
        chooseDataChangeMsg: "请选择一条数据进行数据转换",
        sceneDataMsg: "此操作将把场景对应数据更新到版本对应数据中去【场景时间范围内数据】?",
        conversionSucceeded: "转换成功",
        cancelConversion: "已取消转换",
        copySuccess: "复制成功",
        cannotEmptySheet: "不能清空Sheet",
        sheetUpdateOrNotMsg: "是否放弃当前页签的修改？",
        reNameSuccess: "重命名成功",
        inputRemarks: "请输入备注",
        chooseReasonCode: "请选择原因代码。",
        first: "已经是第一条了！",
        last: "已经是最后一条了！",
        inputParamNameMsg: "请先输入参数名！",
        paramNameRe: "参数名不允许重复！",
        paramNameOrParamValueIsNullMsg: "参数名与参数值都为空的数据将被删除！",
        inputOperatorNameMsg: "请输入运算功能名称",
        chooseOperatorTypeMsg: "请选择运算类型",
        chooseSourceStoryMsg: "请选择源计划故事",
        chooseTargetStoryMsg: "请选择目标故事",
        chooseSourceStoryVersionMsg: "请选择源计划版本",
        chooseTargetStoryVersionMsg: "请选择目标计划版本",
        chooseSourceModelMsg: "请选择源计划模型",
        chooseTargetModelMsg: "请选择目标计划模型",
        chooseSourceMeasureMsg: "请选择源度量",
        chooseTargetMeasureMsg: "请选择目标度量",
        chooseSourceDimensionMsg: "请先选择源维度",
        chooseTargetDimensionMsg: "请先选择目标维度",
        copyDimensionAndRelationMsg: "请完善复制维度与关联",
        inputOperatorTypeMsg: "请输入活动名称",
        chooseOperatorStroyMsg: "请选择故事",
        inputDeviationPeriodPositiveIntegerMsg: "偏移期间量请输入整数",
        inputDeviationRangePositiveIntegerMsg: "偏移范围请输入正整数",
        chooseBeforeOperatorMsg: "请先选择运算功能",
        editData: "请至少编辑一条数据",
        chooseOperatorMsg: "请选择运算功能!",
        operatorRepeatMsg: "运算功能不允许重复选择",
        maintainDimensionMsg: "没有需要维护的维度",
        maintainMeasureMsg: "没有需要维护的度量",
        supplyChainNetworkParametersMsg: "供应链网络参数没有全部维护完成",
        chooseComputingMethodMsg: "请选择计算方法",
        chooseForecastWriteOffMsg: "请选择预测冲销",
        chooseForecastWriteOffOperatorMsg: "请选择预测冲销运算功能",
        chooseDemandResponseMsg: "请选择需求答复",
        chooseDemandPriorityMsg: "请选择需求优先级",
        maintainMainInformationMsg: "请先维护主要信息",
        supplyChainNetworParamSuccesMsg: "供应链网络参数操作成功",
        chooseConsumeModeMsg: "请选择时间消耗模式",
        inputFrontConsumePeriodMsg: "请输入向前消耗的期间数",
        inputFrontConsumePeriodPositiveIntegerMsg: "向前消耗的期间数只能整数",
        inputAfterConsumePeriodMsg: "请输入向后消耗的期间数",
        inputAfterConsumePeriodPositiveIntegerMsg: "向后消耗的期间数只能整数",
        choosePeriodBoundaryMsg: "请选择考虑期间边界",
        chooseBoundaryTimeLevelMsg: "请选择边界时间层级",
        chooseEnableForecastWriteOffMsg: "请选择是否启用预测冲销",
        chooseDeleteData: "请选择要删除的数据",
        product: "请选择产品",
        template:"请选择消息模板"
    },
    planningStory: {
        targeStoryName:"目标计划故事名称",
        includeData:'包含数据',
        main:"主要",
        delivery:"从其他版本复制",
        copyFrom:"复制自",        
    },
    modelDesigner:{
        addDimension: "添加新的Dimension",
        addPublicDimension:"添加公用Dimension",
        useMain:"引用主数据",
        dimensionName:"计划维度名称",
        dimensionPro:"Dimension-产品",
        screen:"筛选条件",
        dataManagement:"数据管理",
        editFormula:"编辑公式",
        formulaFun :"公式函数",
        verification:"格式化与校验",
        supportedFormats:"只支持选择格式“.xlsx , .xls , .csv”",
        inportSet:"导入设置",
        clearAll:"清除并覆盖所有数据",
        append:"追加",
        appendUpload:"追加更新",
        publicDimension:'公用维度',
        targeStoryName:"目标计划故事",
        reseatName:"自动重命名",
        ordinaryMeasure:"普通度量Measure",
        computeMeasure:"计算度量Measure",
        noMaintenanceData:"当前未维护数据",
        isEdit:"是否可编辑",
        definition:"计算定义",
        formula:"公式",
        formulaSenior:"高级公式维护界面",
        polymerization:"聚合设置",
        polymerizationType:"聚合模式",
        decompose:"分解模式",
        decomposeFormula:"分解公式",
        decomposeFormulaSet:"分解公式维护界面",
        decimal:'小数点位数',
        threshold:"阈值",
        thresholdSet:"阈值设置",
        thresholdSetMain:"阈值维护",
        importTask: "导入任务",
        exportTemplate: "导出模板",
        exportTask: "导出任务",
        importMode: "导入方式",
        taskName: "任务名称",
        formulaEditor: "公式编辑器",
        choiceFormat: "只支持选择格式",
        unit: "单位",
        currency: "货币",
        unitAndCurrency: "单位/货币",
        fieldType: "格式",
        template:"数据模板",
        datePicker:"日期",
     },
    warningRules: {
        timeAdd: "时间维度累计",
        timeAddLevel: "时间维度累计层级",
        historyStatus: "考虑历史期间",
        modelChoose: "模型选择",
        computeDimension: "计算维度",
        showMeasure: "显示度量",
        dataViewChoose: "数据表 / 视图 选择",
        dataView:"表 / 视图",
        dateDimension: "时间维度",
        computeDimensionField: "计算维度字段",
        field: "字段",
        showMeasureField: "显示度量字段",
        dimensionScreen: "维度筛选",
        ruleConditions: "规则条件",
        ruleGroup: "规则组",
        chooseMeasuer: "选择度量",
        inputValue: "请输入值",
        choosePercentage: "请选择百分比",
        chooseContrastMeasuer: "选择对比度量",
        addMeasure: "增加度量",
        addRuleGroup: "添加规则组",
        absoluteValue: "绝对值",
        percentage: "百分比（%）",
        warnningRuleName: "警告规则名称",
        dataSourceType: "数据源类型",
        severity: "严重度",
        targetWarnningRuleName: "目标警告规则名称",
        dateSource: "数据源",
        warningRule: "警告规则",
        userAssignment: "用户分配",
        messagePush: "消息推送",
        pushType: "推送方式",
        template:"消息模板"
    },
    warningMonitor: {
        measureOrWarnField: "度量 / 警告字段",
        measureValue: "值",
        lastRunTime: "最后运行时间",
        warningDetail: "警告明细",
        low: "低",
        center: "中",
        high: "高"
    },
    supplyChainNetwork: {
        product: "产品",
        productFamily: "产品族",
        locationCategory: "位置类别",
        location: "位置",
        locationFromCategory: "供应源位置类别",
        locationFrom: "供应源位置",
        effective: "是否有效",
        priority: "优先级",
        ratio: "供应配额",
        leadTime: "提前期",
        leadTimeType: "提前期类型",
        validity: "有效期",
        validityStart: "有效期起",
        validityEnd: "有效期止至",
        chooseDate: "选择日期",
        addRow: "增加一行",
        productSourceName: "生产源名称",
        productSourceDesc: "生产源描述",
        factory: "工厂",
        resources: "资源",
        efficiency: "效率",
        valid: "有效",
        invalid: "无效",
        productSourceResources: "生产源资源",
        positionSource: "位置供应源",
        productionSource: "生产供应源",
        visNetwork: "供应链网络查看",
        supplier: "供应商",
        production: "生产",
        customer: "客户",
        automatic:'自动生成',
        ratio0:"供应比率"
    },
    planningView: {
        scenarioDesc:"场景描述",
        objectCategory: "对象类别",
        objectValue: "对象值",
        calendarName: "日历名称",
        calendar: "日历",
        setUp: "设置",
        dataOperation: "数据操作",
        saveData: "保存数据",
        refresh: "刷新",
        simulation: "模拟",
        ordinarySimulation: "普通模拟运行（当前页）",
        planningOperation: "计划运算功能",
        creat: "创建",
        manage: "管理",
        implement: "执行",
        warnning: "警告",
        warningView: "警告查看",
        task: "任务",
        planningViewData: "计划视图数据管理",
        objectName: "对象名称",
        objectDesc: "对象描述",
        calendarDesc: "日历描述",
        validityStart: "有效期从",
        validityEnd: "有效期至",
        saveNewScene: "保存新场景",
        scenarioName: "场景名称",
        operationalConditions: "运算条件",
        saveScene: "保存为场景",
        viewName: "计划视图名称",
        targetViewName: "目标视图名称",
        view: "视图",
        modelManage: "模型管理",
        addModel: "添加模型",
        scenarioManage: "场景管理",
        changeVersionData: "转换为版本数据",
        lastRefreshTime: "最后刷新时间",
        design: "设计",
        versionAndScenario: "版本与场景",
        updateCount: "已修改的数量",
        reasonCode: "原因代码",
        explain: "说明",
        taskDetail: "任务列表",
        running: "运行中",
        completed: "已完成",
        error: "错误",
        taskId: "任务id",
        taskType: "操作类型",
        taskMessage: "信息",
        term: "项",
        simulationCalendar: "模拟日历调整",
        warningList:"警告列表",
        warningName:"警告名称",
        warningNum:"警告数量"
    },
    operationFunction: {
        parameterName: "参数名",
        parameterValue: "参数值",
        operatorName: "运算功能名称",
        operatorType: "运算类型",
        sourceStory: "源计划故事",
        targetStory: "目标故事",
        sourceStoryVersion: "源计划版本",
        targetStoryVersion: "目标计划版本",
        sourceModel: "源计划模型",
        targetModel: "目标计划模型",
        sourceMeasure: "源度量",
        targetMeasure: "目标度量",
        copyDimension: "复制维度与关联",
        sourceDimension: "源维度",
        targetDimension: "目标维度",
        combination: "组合",
        usageMode: "使用模式",
        frontMode: "前台模式",
        backendMode: "后台模式",
        simulationMode: "模拟运算",
        parameter: "参数",
        customParameter: "自定义参数",
        deviationPeriod: "偏移期间量",
        deviationRange: "偏移范围",
        sort: "排序",
        notMaintained: "未维护",
        maintenanceCompleted: "维护完成",
        dataError: "数据错误",
        computingMethod: "计算方法",
        unlimitedCapacity: "无限产能",
        limitedCapacity: "考虑约束的有限产能",
        demandResponse: "需求答复",
        demandPriority: "需求优先级",
        forecastWriteOff: "预测冲销",
        forecastWriteOffOperator: "预测冲销运算功能",
        supplyChainNetworkParam: "供应链网络参数",
        consumeMode: "消耗模式",
        frontConsumePeriod: "向前消耗的期间数",
        afterConsumePeriod: "向后消耗的期间数",
        periodBoundary: "考虑期间边界",
        boundaryTimeLevel: "边界时间层级",
        enableForecastWriteOff: "是否启用预测冲销"
    }
}