export default {
  taskAndTemp: {
    task: '排程任务管理',
    setTask: '排程任务管理参数设置',
    label: {
      scheduleParamTempleCode: '模板编号',
      scheduleParamTempleName: '模板名称',
      scheduleTaskCode: '任务编号',
      scheduleTaskName: '任务名称',
      schedulingModel: '排程模型',
      scheduleParamTemplateId: '排程参数模板',
      hgScpMpsSourceName: '订单筛选规则',
      status: '任务状态',
      runResultName: '执行结果',
      runStartTime: '开始运行时间',
      runTime: '运行时长（分钟）',
      runTips: '提示信息',
      baseDateType: '排程基准日期',
      scheduleStartTime: '排程开始时间',
      scheduleEndTime: '排程结束时间',
      showStartTime: '显示开始时间',
      showEndTime: '显示结束时间',
      dateSplitPointInTime: '日期分隔时间点',
      allocationMethod: '分配方法',
      allocationResource: '分配资源',
      sameMaterialSetTimeZero: '相同物料设置时间为0',
      allocationDirection: '分配方向',
      makeEfficiency: '制造效率',
      makeTimeCalculate: '制造时间计算',
      beforeSetTimeCalculate: '前设置时间计算',
      crossAllocationStartTime: '越过分派开始时间时',
      crossFirstStartTime: '越过最早开始时间时',
      crossAllocationEndTime: '越过分派结束时间时',
      crossFirstEndTime: '越过最晚结束时间时',
      resourceIdIds: '资源',
      setMinTimeWeight: '权重-转款时间最小化',//'设置时间最小化-权重',
      weightResourcePriority: '权重-资源优先度',
      weightMinExternalProcessing: '权重-外协加工最小化',
      weightMinWaitingTime: '权重-订单逾期最小化',
      weightMinMakeTime: '权重-制造效率最优',
      weightSameMaterialPriority: '权重-切线次数最小化',
      operat: '操作',
      populationSize: '种群规模',
      calcIterateCount: '最大迭代次数',
      calcIteratePersistCount: '迭代最优解保持不变,停止迭代',
      calcSumTime: '总计算时长,时间量纲为秒',
      solutionsSum: '解的数量'
    },
    placeholder: {
      scheduleParamTempleCode: '请输入模板编号',
      scheduleParamTempleName: '请输入模板名称',
      siteCode: '请选择工厂编码',
      scheduleTaskCode: '手动填写，校验唯一性',
      scheduleTaskName: '请输入任务名称',
      schedulingModel: '请选择排程模型',
      hgScpMpsSourceName: '请选择订单筛选规则',
      scheduleParamTemplateId: '请选择排程参数模板',
      baseDateType: '请选择排程基准日期',
      scheduleStartTime: '请选择排程开始时间',
      scheduleEndTime: '请选择排程结束时间',
      showStartTime: '请选择显示开始时间',
      showEndTime: '请选择显示结束时间',
      dateSplitPointInTime: '请选择日期分隔时间点',
      remark: '请输入备注',
      allocationMethod: '选择分配方法',
      allocationResource: '选择分配资源',
      sameMaterialSetTimeZero: '选择相同物料设置时间为0',
      allocationDirection: '选择分配方向',
      makeEfficiency: '请输入制造效率',
      makeTimeCalculate: '选择制造时间计算',
      beforeSetTimeCalculate: '选择前设置时间计算',
      crossAllocationStartTime: '选择越过分派开始时间时',
      crossFirstStartTime: '选择越过最早开始时间时',
      crossAllocationEndTime: '选择越过分派结束时间时',
      crossFirstEndTime: '选择越过最晚结束时间时',
      input: '请输入',
      materialCategory: '请选择物料类别'
    },
    text: {
      date: '当前日期',
      baseTime: '排程基准时间',
      base: '基本',
      order: '分配顺序规则集',
      up: '上移',
      down: '下移',
      addRegular: '新增规则',
      regularList: '资源评估规则集',
    },
    dialog: {
      add: '新增排程任务',
      edit: '编辑排程任务',
      tempName: '排程参数模板'
    },
    ruler: {
      scheduleTaskCode: '请输入任务编号',
      number: '请输入数字！'
    },
    message: {
      start: '启动成功',
      scheduleParamTemplateId: '是否根据新选择的排程参数模板覆盖生成新的排程任务参数？'
    },
    tab: {
      first: '基础参数',
      second: '排程方案参数'
    }
  }
}