export default {
  user: {
    closeLeft: '关闭左侧',
    closeRight: '关闭右侧',
    closeOther: '关闭其他',
    closeAll: '全部关闭',
    help: '帮助文档',
    personalCenter: '个人中心',
    changePsd: '修改密码',
    logOut: '退出登录',
    exitTip: '退出登录确认',
    exitContent: '您确定退出登录当前账户吗？',
    exit: '退出',
    oldPsd: '旧密码:',
    oldPsdInput: '请输入旧密码',
    newPsd: '新密码:',
    newPsdInput: '请输入新密码',
    confirmPsd: '确认密码:',
    confirmPsdInput: '请再输入一次密码',
    psdEmpty: '密码不能为空',
    psdNum: '不能低于6位',
    success: '操作成功',
    disPsd: '两次密码不一致',
    userCode: '用户账号',
    userPsd: '用户密码',
    userName: '用户姓名',
    userGroup: '用户组',
    email: '电子邮箱',
    telephone: '用户电话',
    status: '状态',
    placeholder: {
      tenent: '请输入租户',
      site: '请输入Site',
      userCode: '请输入用户账号',
      userPsd: '请输入用户密码',
      userName: '请输入用户姓名',
      userGroup: '请输入用户组',
      email: '请输入电子邮箱',
      telephone: '请输入用户电话',
      status: '请输入状态',
    }
  }
}