export default {
    vapMapping: {
      title: "VAP-MAPPING信息维护",
      label: {
        customerCode:'客户代码',
        customerName:'客户名称',
        customerStyleNo:'款号',
        custNameShort:'客户简称',
        machineType:'机型',
        resource:'设备',
        patternNo:'花型',
        machineTypeOne:'机型1',
        productionRequirementOne:'双组多片1',
        machineTypeTwo:'机型2',
        productionRequirementTwo:'双组多片2',
        machineTypeThree:'机型3',
        productionRequirementThree:'双组多片3',
        color:'成衣颜色代码',
        colorDes:'成衣颜色',
        partCode:'幅位',
        componentCode:'部位',
        screenSetQty:'网板套数',
        screenQty:'网板数量',
        bulkQty:'大货数量',
        printingSize:'印花尺寸',
        transferStyleHours:'转款时间(小时)',
        transferNetHours:'转网时间(小时)',
        transferSizeHours:'转码时间(小时)',
        transferNetTime:'转网次数',
        printingProcess:'工艺类型',
        heatCondition:'过热参数',
        printingEffect:'印花效果',
        level:'级别',
        potentialRisk:'潜在风险',
        resolvent:'解决方法',
        isFilmAdjusted:'是否调整菲林',
        useAirDuct:'是否用风筒',
        usePressMachine:'是否装压拔机',
        cuttingInspect:'裁床是否查片',
        fittingAllSize:'是否通码',
        largeFlowerPosition:'是否大花位',
        singleSizeDelivery:'是否单码送片',
        ptm:'PTM',
        efficiency:'效率',
        dailyProduction:'日产(20H)',
        garmentPosition:'成衣定位',
        sliceAndShovelSlurry:'开片+铲浆',
        spreadingPart:'铺片',
        adhesiveResidue:'粘毛尘',
        ironing:'用烫斗烫',
        foilTransfer:'贴烫金纸',
        foilRemoval:'撕/吹烫金纸',
        beforeSprayingDigital:'喷数码前',
        partPickup:'起片',
        tableCleaning:'擦台',
        total:'共计',
        spreadingPartMethod:'铺片方式',
        flowersInBothSides:'花是否晒两头',
        isHeatStove:'是否过炉',
        evaluationDate:'评估日期',
        remark:'备注',

        printingProcess1:'工艺',
        embSize:'绣花尺寸',
        gaugeQty:'针数',
        patchQty:'贴布数量',
        isSampleApproved:'样板是否批核',
        useThreadTrimmer:'是否用剪线器',
        attention:'注意事项',
        processDifficulty:'工艺难点',
        sam:'SAM',
        samOne:'SAM1',
        sampleEfficiency:'办事效率',
        sampleEfficiencyOne:'办事效率1',
        ieEfficiency:'IE效率',
        ieEfficiencyOne:'IE效率1',
        bulkEfficiency:'大货效率',
        bulkEfficiencyOne:'大货效率1',
        dailyProduction:'日产量(件/10小时)',
        dailyProductionOne:'日产量(件/10小时)1',
        handPairing:'人手搭配',
        handPairingOne:'人手搭配1',
        samTwo:'SAM2',
        sampleEfficiencyTwo:'办事效率2',
        ieEfficiencyTwo:'IE效率2',
        bulkEfficiencyTwo:'大货效率2',
        dailyProductionTwo:'日产量(件/10小时)2',
        handPairingTwo:'人手搭配2',

        productionQtyMax:'订单数量上限',
        productionQtyMin:'订单数量下限',
        productGroup:'生产分组',
        priority:'优先级',
        productionRequirement:'双组多片',
        emb15Ptm:'EMB15_PTM',
        emb20Ptm:'EMB20_PTM',

      },
      placeholder: {
        customerName:'请选择客户',
        machineType:'请选择机型',
        materialTypeCode: "请选择布种",
        materialTypeName: "请选择布种名称",
        specificationName: "请选择厚度名称",
        sunit: "请输入克重",
        level: "最多保留两位小数",
        productionQtyMax: "请大于下限",
        productionQtyMin: "请小于上限",
  
      },
      check: {
        customerStyleNo: "客户款号不存在,请重新输入",
        tabel: "请至少添加一条数据",
        groupDelete: "请确定是否取消分组",
        productionRequirementGroup: "不同双组多片不能合并，请重新维护！",
        productionRequirementGroupChai: "不同分组多片不能拆分，请重新维护！",
        productionRequirementGroupTrue: "合并成功！",
        table: "同一机型下所选择的双组分片只能小于或等于四组！",
        priority: "优先级只能 为1级、2级、3级！",
      },
      selectCommon: {
        emb: "绣花",
        embD: "绣花模板",
        printing: "印花",
        printingD: "印花模板",
        transferNetTime:'转网次数维护',
        transfer:'优先级设置',
        group:'生产分组新增/编辑',
        risk:"生产风险评估",
        produce:'生产前配套需求',
        production:'产量预计',
        manpower:'人手搭配',
      },
      ruler:{
        numRange:'请输入大于0的整数',
        numRanges:'请输入大于等于0的整数',
      }
    }
  }
  
  
  